# Generated by Django 4.2.27 on 2025-12-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationnote_candidatecommunication_candidatetag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='JSON snapshot of resume data at time of application'),
        ),
    ]
