# Generated by Django 4.2.27 on 2025-12-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_resume_snapshot'),
    ]

    operations = [
    ]
