# Generated by Django 4.2.27 on 2025-12-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20251226_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume_snapshot',
            field=models.FileField(blank=True, help_text='Resume used at time of application', null=True, upload_to='application_resumes/'),
        ),
    ]
