# Generated by Django 4.2.27 on 2025-12-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_resume_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='experience_summary',
        ),
        migrations.AddField(
            model_name='application',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict, help_text='Additional application info like driving license, etc.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='Skills with ratings in this application'),
        ),
    ]
