# Generated by Django 4.2.27 on 2026-01-02 08:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobseeker_github_url_jobseeker_linkedin_url_and_more'),
        ('applications', '0007_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='interview_completed',
        ),
        migrations.RemoveField(
            model_name='application',
            name='interview_notes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='interview_scheduled',
        ),
        migrations.AddField(
            model_name='interview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_interviews', to='accounts.recruiter'),
        ),
        migrations.AddField(
            model_name='interview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('phone', 'Phone Screen'), ('video', 'Video Call'), ('onsite', 'On-site Interview'), ('technical', 'Technical Assessment')], default='video', max_length=50),
        ),
    ]
