# Generated by Django 4.2.27 on 2026-01-02 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobseeker_github_url_jobseeker_linkedin_url_and_more'),
        ('applications', '0008_remove_application_interview_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('phone', 'Phone Screen'), ('video', 'Video Call'), ('onsite', 'On-site Interview'), ('technical', 'Technical Assessment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_interviews', to='accounts.recruiter'),
            preserve_default=False,
        ),
    ]
