# Generated by Django 4.2.27 on 2026-01-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_interview_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hired_date',
            field=models.DateTimeField(blank=True, help_text='Date when candidate was officially hired', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='new', max_length=20),
        ),
    ]
