# Generated by Django 4.2.27 on 2026-01-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_application_hired_date_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='notification_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status', 'scheduled_date', 'notification_reminder_sent'], name='application_status_855745_idx'),
        ),
    ]
