# Generated by Django 4.2.27 on 2025-12-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_salary_range_job_benefits_job_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(default='IT', max_length=255),
            preserve_default=False,
        ),
    ]
