# Generated by Django 4.2.27 on 2025-12-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_messageattachment_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['job'], name='chat_conver_job_id_2dc0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['recruiter', 'job_seeker', 'job'], name='chat_conver_recruit_16fc6e_idx'),
        ),
    ]
