# Generated by Django 4.2.27 on 2025-12-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobseeker_github_url_jobseeker_linkedin_url_and_more'),
        ('applications', '0006_remove_application_experience_summary_and_more'),
        ('chat', '0004_alter_conversation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('application', 'recruiter', 'job_seeker')},
        ),
    ]
