# Generated by Django 4.2.27 on 2025-12-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobseeker_github_url_jobseeker_linkedin_url_and_more'),
        ('jobs', '0006_alter_department_options_alter_job_options_and_more'),
        ('chat', '0005_alter_conversation_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_job_id_2dc0ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_recruit_16fc6e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('recruiter', 'job_seeker', 'job')},
        ),
    ]
