# Generated by Django 4.2.27 on 2025-12-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobseeker_github_url_jobseeker_linkedin_url_and_more'),
        ('chat', '0006_remove_conversation_chat_conver_job_id_2dc0ee_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('recruiter', 'job_seeker')},
        ),
    ]
