# Generated by Django 4.2.27 on 2025-12-24 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='driving_license',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='last_location_update',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='vehicle_plate_number',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('recruiter', 'Recruiter'), ('job_seeker', 'Job Seeker')], default='job_seeker', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='e.g. HR Manager, Talent Acquisition', max_length=100)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
