# Generated by Django 4.2.27 on 2025-12-25 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_jobseeker_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to=settings.AUTH_USER_MODEL),
        ),
    ]
