# Generated by Django 4.2.27 on 2025-12-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_recruiter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='phone_number',
            field=models.CharField(default=9800000000, max_length=15),
            preserve_default=False,
        ),
    ]
