# Generated by Django 4.2.27 on 2026-01-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobseeker_github_url_jobseeker_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='bio',
            field=models.TextField(blank=True, help_text='Recruiter bio/introduction'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='department',
            field=models.CharField(blank=True, help_text='Department', max_length=100),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter_profile_pictures/'),
        ),
    ]
